### ISSUE TITLE
Improve colorRegionDetection and haarDetection documentation

### ISSUE THREAD

**Issue by jmgarciah** [roboticslab-uc3m/teo-head#10]
Documentation currently hosted at:

* http://robots.uc3m.es/dox-vision/group__haarDetection.html
* http://robots.uc3m.es/dox-vision/group__colorRegionDetection.html

Lacks information regarding
- [X] Configuration parameters on init
- ~~Input ports and contents~~
- [X] Output ports and contents

**Comment by jmgarciah** [comment]
PS: --noMirror parameter should be documented at doxygen and code level.

**Comment by rsantos88** [comment]
Added tables with parameters of cv1 and cv1Faces documented at doxygen in the next pull request: d23a265abde84f78f2e194b366179f4965759fb6

**Comment by jgvictores** [comment]
Here's some pointers on a description to be added to what currently is cv1 (may change name! see #22):
It's mainly composed by: classical morphological operations, some kind of binary thresholding, then opencv blobs/contours...

**Comment by dpriver** [comment]
The links are down.
It would be really useful to include examples in the documentation.

**Comment by PeterBowman** [comment]
@Kuronogard fixed (changed `dox-teo-head` to `dox-vision`).

**Comment by PeterBowman** [comment]
> Added tables with parameters of cv1 and cv1Faces documented at doxygen in the next pull request: [d23a265](https://github.com/roboticslab-uc3m/vision/commit/d23a265abde84f78f2e194b366179f4965759fb6)

The original requests have been fulfilled, docs may be always improved thereafter - hence closing.
