### ISSUE TITLE
Prepare Docker image for CI

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/teo-head#107]
CI support via GitHub Actions was added at https://github.com/roboticslab-uc3m/vision/commit/f87fbd1cdb45cd8764d1b1e88e4d16724438f4ad. Currently, some components are excluded from the build due to unmet dependencies, which ultimately boils down to not having OpenCV compiled from sources. Instead, we consume the official [*libopencv-dev* apt package](https://packages.ubuntu.com/search?keywords=libopencv-dev). For reference, OpenCV 3.2.0 is provided in Bionic, and 4.2.0 in Focal.

These components are:

- [DnnDetector](https://github.com/roboticslab-uc3m/vision/tree/f87fbd1cdb45cd8764d1b1e88e4d16724438f4ad/libraries/YarpPlugins/DnnDetector): the dnn module was not bundled with the apt package until the 4.0 release.
- [QrDetector](https://github.com/roboticslab-uc3m/vision/tree/f87fbd1cdb45cd8764d1b1e88e4d16724438f4ad/libraries/YarpPlugins/QrDetector): requires OpenCV 4.x, yet additional linkage is necessary against an external library (QUIRC).
- [sceneReconstruction](https://github.com/roboticslab-uc3m/vision/tree/f87fbd1cdb45cd8764d1b1e88e4d16724438f4ad/programs/sceneReconstruction): requires the rgbd module from opencv_contrib and enabling support for non-free algorithms.

Idea: prepare a Docker image that contains the most adequate OpenCV release with all necessary modules and dependencies, and upload it to https://github.com/orgs/roboticslab-uc3m/packages for use in CI via GH Actions in this repo.

Note that it is actually interesting to have several OpenCV versions to test against, especially the 3.x one. Doable via Docker tags?

Besides, such image would not be that useful beyond CI. Perhaps we could go a step further and prepare another one that contains a working build of roboticslab-uc3m/vision libraries and tools?

**Comment by jgvictores** [comment]
> Besides, such image would not be that useful beyond CI. Perhaps we could go a step further and prepare another one that contains a working build of roboticslab-uc3m/vision libraries and tools?

I believe that the Docker image, even without a working build of roboticslab-uc3m/vision libraries and tools, would be useful for user land. Two use cases:

- In the case of compiling roboticslab-uc3m/vision, if I'm not getting everything wrong and the equivalence not too is far-fetched, I'd say this is similar to what you achieve with a `apt-get build-dep` workflow.
- We also have some parallel developments going on in ROS world, which installs its own version of OpenCV. Help for compiling against modern OpenCV with Dnn and Qr would be excellent.

**Comment by PeterBowman** [comment]
Might be useful: https://github.com/Jimver/cuda-toolkit (a GH action to install CUDA).

**Comment by PeterBowman** [comment]
Info:
- https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
- https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows
- https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by PeterBowman** [comment]
Done at https://github.com/roboticslab-uc3m/vision/commit/738078a20e2e6497fba53cffd47920052fc3ba50. A new [workflow](https://github.com/roboticslab-uc3m/vision/blob/738078a20e2e6497fba53cffd47920052fc3ba50/.github/workflows/docker.yml) builds the [Dockerfile](https://github.com/roboticslab-uc3m/vision/blob/738078a20e2e6497fba53cffd47920052fc3ba50/docker/Dockerfile) and pushes its image to GHCR. It is available [here](https://github.com/roboticslab-uc3m/vision/pkgs/container/vision) in two flavors:

- `docker pull ghcr.io/roboticslab-uc3m/vision:ubuntu-20.04-opencv-4.x`
- `docker pull ghcr.io/roboticslab-uc3m/vision:ubuntu-22.04-opencv-4.x`

Latest OpenCV's `4.x` branch is built in it (currently 4.10) along with all `apt` dependencies (most notably, PCL). Our CI builds now pull this image and run all tests against a temporary container.

**Comment by PeterBowman** [comment]
ROS 2 added at https://github.com/roboticslab-uc3m/vision/commit/d908664bd45ae6e70cda977c587d5588cd831426. It is used in rgbdDetection to publish detected 3D points via ROS (this was authored by @anacg1620 in an old branch I restored and migrated from ROS 1 to ROS 2): https://github.com/roboticslab-uc3m/vision/commit/10ef07bb939294adbc9b8b42565bcf6f82a22cb3.
