### ISSUE TITLE
Avoid "using namespace" to avoid namespace conflicts

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/teo-head#13]
Use alternatives such as:
- Not using "using namespace"
- Using named namespaces (similar to Python's "import x as y")

**Comment by jgvictores** [comment]
Totally agree.
+1 to Not using "using namespace".

**Comment by David-Estevez** [comment]
@rsantos88 cv::vector does the same as std::vector ?? (Commit 0807c9ebd90d30709b6c519760a1b2d619a800b6 )

**Comment by rsantos88** [comment]
@David-Estevez in this moment, there are not “using namespace” in teo-head proyect and the code compiles perfectly but is necessary to create a tests system for checking if the programs work well.

**Comment by David-Estevez** [comment]
cv::vector might be due to a "using namespace" inside OpenCV, that has added all std:: members to the cv:: namespace.

@rsantos88 cv::vector should be replaced by std::vector in all instances.

**Comment by rsantos88** [comment]
@David-Estevez  Now cv::vector has been replaced by std::vector in all instances of teo-head (Commit c950343ed9c23dbf1a839c81225cb0b5cfbcf4c4)

**Comment by David-Estevez** [comment]
@jgvictores could you test this refactoring before merging with the main branch?

**Comment by jgvictores** [comment]
Tried and merged at 4a34f5e7826b5dae5383c2bbfebd7143447524d2.
