### ISSUE TITLE
Error compiling cv1: /usr/bin/ld: cannot find -lQt5::Widgets

### ISSUE THREAD

**Issue by lpinel** [roboticslab-uc3m/teo-head#15]
Error compiling cv1 on Ubuntu 14.04.3 LTS (teo-main PC, but ok on teo-head PC):
/usr/bin/ld: cannot find -lQt5::Widgets
Issue may be related to VTK.

**Comment by jgvictores** [comment]
On same PC, fixed by setting -DYARP_USE_QT5=OFF on YARP.
Will close issue once documented or fixed upstream.

**Comment by jgvictores** [comment]
Documented at db010bf028eeb4b266deda7b57e6f29547a071d3, but should still check if issue should be put upstream (robotology/yarp).
