### ISSUE TITLE
[cv1] seeBounding parameter documentation does not match implementation

### ISSUE THREAD

**Issue by jmgarciah** [roboticslab-uc3m/teo-head#16]
Doumentation reads:
`--seeBounding (0=none,1=box,2=contour,3=both)`
While travis.getCvMat second parameter (to which seeBounding is passed) provides:
`0=none,2=box,1=contour,3=both`

**Comment by rsantos88** [comment]
Thanks. Now, everything is corrected (9d6a6c7e8315581269911e6a030e6a556146846f)
