### ISSUE TITLE
cvFaces should be generalized to haarDetection

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-head#19]
Making haar cascade xml a parameter would extend the module capabilities way beyond faces.

**Comment by rsantos88** [comment]
Added different types of xml hardcascade in cvFaces. Now, you can configure the program using “–xmlCascade” parameter, continued the filename of hardcascade. All the possibles XML files of hardcascade are located in https://github.com/Itseez/opencv/tree/master/data/haarcascades
You can see this changes in #25

**Comment by jgvictores** [comment]
Done at https://github.com/roboticslab-uc3m/teo-head/commit/465644ac754676d1b454fc8deb5b6625f45b6ba2.
