### ISSUE TITLE
Cleanup cvFaces from unused parameters

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-head#23]
Cleanup cvFaces from unused parameters (inherited from a copy+paste off cv1).

PS: Note that #19 may involve name change.

**Comment by rsantos88** [comment]
Now, cvFaces is clean of the following parameters: (see: #24)
-algorithm
-locate
-maxNumBlobs
-morphClosing
-outFeaturesFormat
-outFeatures
-outImage
-threshold
-seeBouncing
-morphOpening
-fx_rgb
-fy_rgb
-cx_rgb
-cy-rgb
