### ISSUE TITLE
[FollowMe] Improving demo

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-head#34]
Propongo la posibilidad de mejorar la demo de "Follow me" (puesto que actualmente es la única que está operativa) añadiendo algo más credibilidad y vistosidad para cuando alguien quiera ver a Teo. Por ejemplo, se pueden intentar añadir cosas "sencillas" como acompañar el balanceo permanente de brazos por la posibilidad de que al principio el robot mueva el brazo (gesticulando) a la vez que dice "ok, I am following you".

**Comment by jgvictores** [comment]
@rsantos88 Could you please post this as an issue in the [follow-me repository](https://github.com/roboticslab-uc3m/follow-me) and close it here?

Thanks!!

**Comment by rsantos88** [comment]
Ok @jgvictores. Sorry :)
