### ISSUE TITLE
The frontal movement it's not working

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-head#37]
Al tratar de mover la cabeza frontalmente, ésta no se mueve. En cambio al revisar la posición de la articulación a través del encoder relativo, este marca correctamente los grados a los que se le ha mandado moverse.

**Comment by jgvictores** [comment]
Tiene pinta de motor quemado o conectores/cables mal...

BTW, lo dejamos aquí, pero esto sería un poco más teo-body :smile:

**Comment by rsantos88** [comment]
Arreglado. Gracias! :+1:
