### ISSUE TITLE
[tts] Create yarp device that wraps espeak

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-head#38]
As addressed in https://github.com/roboticslab-uc3m/teo-main/issues/55 the pipe solution of https://github.com/roboticslab-uc3m/teo-main/blob/e0e47c2fc6b3cc40fceffefc075ae811ec0b9b99/share/teoBase/scripts/teoBase.xml#L46-L56 is relatively evil (will not be managed correctly by yarpmanager, and will not be closed correctly as there are two processes and not one).
Create a wrapper of [espeak](http://espeak.sourceforge.net/) similar to https://github.com/robotology/speech/tree/master/svox-speech.

**Comment by rsantos88** [comment]
After following the steps, when I try to do "cmake.." in ../espeakExample/build, it says:

> By not providing "FindTEO_HEAD.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "TEO_HEAD",
>   but CMake did not find one.
> 
> Could not find a package configuration file provided by "TEO_HEAD" with any
>   of the following names:
>     TEO_HEADConfig.cmake
>     teo_head-config.cmake
> 
> Add the installation prefix of "TEO_HEAD" to CMAKE_PREFIX_PATH or set
>   "TEO_HEAD_DIR" to a directory containing one of the above files.  If
>   "TEO_HEAD" provides a separate development package or SDK, be sure it has
>   been installed.

I have opened the .bashrc script and It shows the last line with the path:

> export TEO_HEAD_DIR=/repos/rsantos88/teo-head/build

What can I do?

**Comment by jgvictores** [comment]
Please paste the output of:

``` bash
tail -5 ~/.bashrc
echo $TEO_HEAD_DIR
ls $TEO_HEAD_DIR
```

**Comment by jgvictores** [comment]
Wait just a sec. `TEO_HEAD_DIR` needs the full path. Pre-pend `/home/YOUR_USER_NAME/` to it.

**Comment by rsantos88** [comment]
I just tried to put the full path and it works ok. Thanks @jgvictores

**Comment by jgvictores** [comment]
:smiley:

**Comment by jgvictores** [comment]
Lots done at a2be7f8a63b8c285a70ee174bdb0135b9a23cb98.
Missing:
- [x] Set default port full name to /tts/rpc:s
- [x] Example app
- [x] Update follow-me
- [x] Update waiter?
