### ISSUE TITLE
Refactor CMake files

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-head#7]
A great number of new CMake features would make our CMake files cleaner and better.

**Comment by PeterBowman** [comment]
Previously on (show name)...

* roboticslab-uc3m/kinematics-dynamics#14
* roboticslab-uc3m/yarp-devices#26
* roboticslab-uc3m/openrave-yarp-plugins#56

**Comment by PeterBowman** [comment]
Done at cac6420.

**Comment by jgvictores** [comment]
@PeterBowman Thanks a lot! I'm (hopefully) going to be touching this repo quite a bit this week, so this comes at a very good moment!
