### ISSUE TITLE
Set pointAtObjectServer ON, and if PCL is not found, show warning and disable

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-head#78]
As a followup of 887d5e4aa4494d7c0c69168bfcaa428f82398f7c, beter to have pointAtObjectServer ON, and if PCL is not found, show warning and disable.

**Comment by jgvictores** [comment]
Related: https://github.com/roboticslab-uc3m/questions-and-answers/issues/18#issuecomment-361898108

Also see: https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/138#issuecomment-361898436

**Comment by jgvictores** [comment]
Help at! https://github.com/roboticslab-uc3m/questions-and-answers/issues/18#issuecomment-362724497

**Comment by PeterBowman** [comment]
Applied https://github.com/roboticslab-uc3m/questions-and-answers/issues/18 at cf66378.

**Comment by jgvictores** [comment]
@PeterBowman Thanks a lot!!
