### ISSUE TITLE
Error Compilation - teo-head

### ISSUE THREAD

**Issue by ghost** [roboticslab-uc3m/teo-head#8]
In file included from /home/jgarciah/git/teo-head/programs/cv1/SegmentorThread.hpp:14:0,
                 from /home/jgarciah/git/teo-head/programs/cv1/SegmentorThread.cpp:3:
/usr/local/include/yarp/dev/IOpenNI2DeviceDriver.h:16:18: fatal error: NiTE.h: No such file or directory
 #include <NiTE.h>
                  ^
compilation terminated.
make[2]: **\* [programs/cv1/CMakeFiles/cv1.dir/SegmentorThread.cpp.o] Error 1
make[1]: **\* [programs/cv1/CMakeFiles/cv1.dir/all] Error 2
make: **\* [all] Error 2

**Comment by jgvictores** [comment]
Fixed at faff071f11da3fa8ce5519d5bc8c8a1d3332ea85.
