### ISSUE TITLE
Missing libtiff4-dev package on Ubuntu 16.04 (needed by OpenCV3)

### ISSUE THREAD

**Issue by jmgarciah** [roboticslab-uc3m/teo-head#81]
when you want to install on 16.04, it is not detected.

$ sudo apt-get install libtiff4-dev

could it be a possible solution the lib "libtiff5-dev" ¿?¿?

**Comment by PeterBowman** [comment]
Our guides ([ref](https://github.com/roboticslab-uc3m/installation-guides/blob/349a48be4b9768089901eeb97d85264e239c123f/install-opencv.md#install-opencv-3-with-contrib-and-python-3-support)) state that `libtiff4-dev` is needed, but, as you pointed out, there is no such package on Xenial. On the other hand, `libtiff5-dev` is available from Trusty onwards:

* https://packages.ubuntu.com/search?keywords=libtiff4-dev
* https://packages.ubuntu.com/search?keywords=libtiff5-dev

Official guides recommend installing `libtiff-dev`, which redirects to `libtiff5-dev` on those systems:

* https://docs.opencv.org/3.0-beta/doc/tutorials/introduction/linux_install/linux_install.html
* https://packages.ubuntu.com/search?keywords=libtiff-dev

**Comment by jgvictores** [comment]
@jmgarciah Hi! Thanks for pointing this out!

> could it be a possible solution the lib "libtiff5-dev" ¿?¿?

@jmgarciah Yes, that is a possible solution!

> Official guides recommend installing libtiff-dev, which redirects to libtiff5-dev on those systems:

@PeterBowman Great finding, thanks! I've updated at https://github.com/roboticslab-uc3m/installation-guides/commit/57cd9733c80312a262fd8b8d7b71fd10a95b999a to provide this more portable solution.


@jmgarciah Feel free to close this issue if you got things working on the libtiff side!

**Comment by jmgarciah** [comment]
thx to @PeterBowman and @jgvictores
