### ISSUE TITLE
Compiling error when importing freenect on Python

### ISSUE THREAD

**Issue by FernandoM93** [roboticslab-uc3m/teo-head#84]
I'm trying to use the Kinect camera with python. I have installed "Python 3.6.4 :: Anaconda, Inc.", and OpenKinect.
OpenKinect was installed following the next tutorial:
https://openkinect.org/wiki/Getting_Started#Ubuntu.2FDebian
OpenKinect seems to be working well because when i run freenect-glview, it works perfectly (including motors, leds, etc).
The problem comes when i try to run a program in python. The error that appear is the next one:
```
import freenect

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-edb8594d279a> in <module>()
----> 1 import freenect

ImportError: No module named 'freenect'

```
It looks like the library freenect is not correctly linked with python.

I'm using Ubuntu 16.04

@jgvictores

**Comment by jgvictores** [comment]
The setup we are supporting for is via YARP as documented [here](https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-yarp.md#install-additional-yarp-device-openni2deviceserver-ubuntu). You can then get Python bindings as documented [here](https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-yarp.md#install-python-bindings).

1. If you have any issue with those instructions for that process, please post an issue on: https://github.com/roboticslab-uc3m/installation-guides
1. If you prefer to proceed with libfreenect directly via Python, remember that:
   - That is not a compilation issue, it is a missing module during interpreted run-time
   - Anaconda uses its own package managing system, and you can easily end up with a mix of many Python versions
   - You should post issues on https://github.com/OpenKinect/libfreenect or https://stackoverflow.com
