### ISSUE TITLE
ASUS CAMERA CONECTION

### ISSUE THREAD

**Issue by ghost** [roboticslab-uc3m/teo-head#9]
In the lab computer of Juan H, Juan can not connect the camera.

**Comment by jgvictores** [comment]
Could you copy the output of the following command (with the Asus Xtion Pro Live connected)?
yarpdev --device OpenNI2DeviceServer --noMirror --depthVideoMode 4 --colorVideoMode 9

**Comment by jgvictores** [comment]
Issue fixed by disconnecting and connecting the USB 3.0 cable.
This driver issue could possibly be addressed by further research on driver init rules.
