### ISSUE TITLE
Add HAAR training dataset files to Google Drive folder 

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-head#91]
As a followup of #90, current https://github.com/roboticslab-uc3m/vision/blob/1fe57713d2e839769cb601f0ed007424588135b6/share/haarDetection/conf/README.md points at https://drive.google.com/drive/folders/1gYGtfsKGi0_505JAHBiivdGd9Exue57F?usp=sharing which currently has the correct folder structure, but is lacking the contents (files).

Task: Add HAAR training dataset files to Google Drive folder.

**Comment by davidvelascogarcia** [comment]
All the files that I have been able to recover have been uploaded to the [Google Drive folder](https://drive.google.com/drive/folders/1gYGtfsKGi0_505JAHBiivdGd9Exue57F?usp=sharing).

**Comment by jgvictores** [comment]
Great, thanks!
